name: terminal_view
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lxd:
    git:
      url: https://github.com/jpnurmi/lxd.dart
      ref: 9799464c4488f52203407169baca963f88f0e349
  xterm:
    git:
      url: https://github.com/jpnurmi/xterm.dart
      ref: 085c9acafcec02bdf2b61aa49e013d6b3cfc1480

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
