name: osarch
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  meta: ^1.7.0
  stdlibc:
    git:
      url: https://github.com/jpnurmi/stdlibc.dart.git

dev_dependencies:
  mockito: ^5.2.0
  test: ^1.21.1
